# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a609b28f35d25d5f1bc37be400d7ab13e531c3ff4e59924e9a7bd340f65838a95be2972fbcd7c7e0a9c696456ae153b67140c0bfe912ca8641b4505beeb4f451

test:
  secret_key_base: 3ce1e2850fe48a2f356b517c03ccef8a090ea619343c32c4624d5abc2da5cb8c49b4dbd182959ffcf4b6fe4d679c2cbfd518d014e6ed9785b11c6af8d9c87300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
